### ISSUE TITLE
[PROPOSAL] Add router extension to automatically serialize returned entities

### ISSUE THREAD

**Issue by Evertt** [laravel-doctrine/orm#188]
In Laravel, when you return an eloquent model from a controller-method or a closure, the router will automatically make sure that it's serialized. Like this:

``` php
Route::get('/api/users/{user}', function (\App\User $user) {
    return $user;
});
```

I would like to have a router-extension which does the same for Doctrine models. This proposal, together with the other one I made (#187), can help make the code as beautiful as it now is with Eloquent models.

**Comment by maxbrokman** [comment]
Automatic serialization of Doctrine entities makes me a bit uncomfortable. It certainly makes more sense for Eloquent because a model is a simple mapping to a database row (with a little bit of type coercion). But for Doctrine it's possible to have more complex relationships with arbitrary nested objects (embeddables etc).

If you were to do this it should check for `Jsonable` before trying to do anything.

Can you point me to where Laravel is doing the serialization?

**Comment by patrickbrouwers** [comment]
You can use the trait (https://github.com/laravel-doctrine/orm/blob/1.2/src/Serializers/Jsonable.php), but I would really advise against coupling your API response to your entities. Consider using transformers (like Fractal) instead.

**Comment by Evertt** [comment]
To be honest I'm not so experienced with Doctrine. I only worked with it in one project, using Symfony, but all the setup was done by another guy. Anyhow, in that project all the serialization was configured by YAML files. So I figured, we could do a similar thing here, right?

By that I mean, have some configuration somewhere, where you define how every entity should be serialized. And then in your controllers or route-closures you can simply return the entity and the router-extension will do the rest.

**Comment by patrickbrouwers** [comment]
Not YAML, but more or less the same end-result: http://fractal.thephpleague.com/ 

I would go for explicit transformations rather than depending on some magic (sucks to debug).
