### ISSUE TITLE
[request] integration with laravel passport

### ISSUE THREAD

**Issue by Evertt** [laravel-doctrine/orm#189]
The title says it all. We need a replacement for the `Laravel\Passport\HasApiTokens` trait for example.
## edit

or would this better fit in the extensions repo?

**Comment by patrickbrouwers** [comment]
I have looked into it just after it was released and it seemed like a lot of work. (Maybe I'm wrong). I currently don't need it myself and I'm very busy at the moment. If anybody wants to PR it, I'm happy to setup a repository for it.

**Comment by ghost** [comment]
For a project of mine I have partially ported passport to doctrine... At least password grants and authentication works, but not much more as of now. Also, I am quite unexperienced with laravel...
I could publish it, so we could work on this together.

But a short disclaimer: It was impossible to reuse anything from passport. More or less, I just copied the source and manually changed everything to use doctrine interfaces. So this project would have to be maintained completely independent from passport...

We would also have to rethink some aspects like configuration etc... I mostly hardwired everything to get the basics to work.

I think that it would be a good codebase to start with, but still, it needs one or two days of work to publish it. But I don't want to maintain this just by myself, so if anybody could help me, I would be grateful. 

@patrickbrouwers If you're interessted, I could make a PR for the repo you mentioned (I have seen that a repo already exists, but it is empty and can't be forked therefore)

**Comment by patrickbrouwers** [comment]
@christiandreher if you can share the repo through your own github, I can have a look if it's in the right direction :) 
Ping me on our slack.

**Comment by ghost** [comment]
@patrickbrouwers All right, I will try to do that on monday. Thanks for the response

**Comment by Toyinster** [comment]
Hi, I wondered if there was any update in this please?

**Comment by ghost** [comment]
@Toyinster I have published my first codebase [here](https://github.com/christiandreher/passport-doctrine), but I did not yet receive any feedback. 

I will continue working on this as the requirements for my project change, but for now this is enough for me... Wish that I could invest more time in this project, but I cant, I'm sorry

**Comment by oddz** [comment]
I started looking at this myself and I don't believe you need to copy the entire passport package and jerry rig the solution. I was reading through the OAuth2 docs and everything seems to be based on interfaces. If that is true than in theory all the entities can be replaced doctrine specific entities and repositories. I think that can be done via using a custom service provider instead of porting and changing the entire passport package. Although I have just started to look at the code.

**Comment by oddz** [comment]
I need to have this for something I'm currently working on. So I have began scaffolding out a package.

https://github.com/oddz/doctrine-passport

I figure since everything uses interfaces it shouldn't be to difficult to replace the existing implementation using container interface bindings.

**Comment by oddz** [comment]
I'm starting to see the problem. About 80% of the code is using eloquent without abstraction. Hmm... perhaps christiandreher has the right approach with this.

**Comment by ghost** [comment]
Yes, the problem for me was that the API of the lib by phpleague is quite complex, and passport already figured out how to use it. I therefore thought that it would be the most simple, and the most save (!) approach to port it to doctrine. Passport seems to be well established...

I know that its not perfect, especially if there is a security leak or anything, but we could either implement everything by ourselves (on top of phpleagues lib of course), or use the existing, well-established approach by passport as skeleton and replace everything with doctrine-standards until we have our own OAuth2 service provider. 

At least this is what I thought. Sorry for responding so late, but I was busy until now

Btw: I think that we (everyone interested in this, like me, @oddz, etc and especially laravel-doctrine) should combine our efforts instead of everyone working on it's own half-baked solution. I would therefore highly appreciate, if some admin of laravel-doctrine could supervise and coordinate this. I think that this would be best for all of us. I do not say that I have the right approach or anything, I am just interested in the result, so if anyone has a better idea I will be the last refusing to cooperate

CC @patrickbrouwers (sorry, I don't know how I should raise attention otherwise)

Edit: @oddz: The problem by itself is not with phpleagues lib, which already implements OAuth2 very good, but rather with the integration with laravel/lumen. Passport has a good integration with laravel/lumen, but it depends on eloquent. So the problem is one abstraction layer above the OAuth2 implementation, exactly where passport uses eloquent. But, to be fair, it would be strange if they would use a database-abstraction-abstraction-layer :D

**Comment by oddz** [comment]
Yeah, the problem with yours is it really isn't a reusable package. Its really just something to reference and copy and paste into ones own project. I would like to build a complete drop in replacement and where possible reuse/extend the core passport package architecture. Although like you said that can be difficult in places due to the tight coupling with Eloquent. Either way I think that all starts with a better understanding of leagues oAuth2. I started looking over that documentation and have a much better understanding of what needs to be done.

**Comment by ghost** [comment]
I wanted to publish it in the end for composer, so it would actually work like that, but I thought that it is more important to get the basics running instead of publishing it prematurely

**Comment by patrickbrouwers** [comment]
I looked at Passport when it came out and already noticed it would be a lot of work, so didn't proceed bridging it.

I'd suggest joining our slack and ask for people's help there. Not everyone reads all github issues :)

**Comment by oddz** [comment]
Yeah, its going to be a pain in the butt. However, I think I could probably do it in like 40 – 60 hours and really need it for something I'm working on.

**Comment by SwenVanZanten** [comment]
I need it too.. perhaps I can help

**Comment by oddz** [comment]
Over the next few weeks I'm going to work on it in my repo. The problem is finding the time and motivation after work.

**Comment by oddz** [comment]
I've began creating a package below. Thus far most time has been spent scaffolding out everything. However, anyone is free to fork and help me out with it. It doesn't work at all yet.

https://github.com/oddz/doctrine-passport/tree/master/src/Bridge/Repositories

**Comment by LavaToaster** [comment]
Hey All - I've made a PR that contains what I consider to be a near MVP version of a Laravel doctrine port. https://github.com/laravel-doctrine/passport/pull/1

I'd appreciate it if you could review it. ❤️

**Comment by Evertt** [comment]
@Lavoaster I don't have time to really review your code, but I just want to say I very much appreciate the work you've put into it!

**Comment by patrickbrouwers** [comment]
We have decided to not support any Doctrine implementation of Passport. Instead we suggest using it with Eloquent, and mapping it to Doctrine after the authentication is done.

Link to slack discussion: https://laraveldoctrine.slack.com/archives/C07HD2RS7/p1488372497003072

I'll be updating the readme/docs soon to indicate how you should integrate with Passport.

**Comment by oddz** [comment]
That's sad. A great community of devs just saying fuck it because core doesn't easily cater to integration with Laravel doctrine. I think laravel doctrine is one of the best initiatives to advance the Laravel. I mean let's face it... as great as Laravel is Eloquent is several years behind the times. Eloquent, active record in general is an out dated persistence mechanism. I can't believe for one second that the great minds who thought of and implemented doctrine into Laravel are happy with no solution to this problem. Especially when you have sch a smart, sophisticated solution right in front of you. Shame on you.

**Comment by oddz** [comment]
Lavaoster has provided a pretty good solution to this problem. It isn't perfect because it can't be due to the rigid architecture of passport. However, it is a try... a try beyond just saying fuck it.

**Comment by oddz** [comment]
I expect better. Especially from great projects I have looked up to and learned a lot from. Icant even fathom right now why doctrine, isn't a pattern to be looked up to. Active record has so many limitations... especially an active record pattern design that is proprietary to such a wonderful, flexible, and forward facing architecture as Laravel within the the context of php development.

**Comment by oddz** [comment]
I meant to say that active record is dead and frameworks like Laravel should be supporting much more flexible persistence layers. Supporting pesistence mechanisms with such a limited feature set, beyond the capabilities of 2009 is only going to make the JavaScript everywhere movement that much more dominant.

**Comment by oddz** [comment]
This is just messed up. Laravel is currently the best, most sophisticated framework in php ecosystem. It's just not acceptable to have people abandon it and suggest using eloquent... Luke I said before an age old, piece of shit persistence layer which should have been left in the glory days of rails...

**Comment by patrickbrouwers** [comment]
Please offer your apologies for your response. I don't accept being responded to in this way.

**Comment by oddz** [comment]
I don't. I love ya guys and what you have done for Laravel, doctrine but this just isn't acceptable.

**Comment by patrickbrouwers** [comment]
I won't help you anymore until you apologize. Your response is completely ridiculous and childish. This decision wasn't taken lightly and you are mocking us for it. You are the one being unacceptable. 
We are in no way required to offer and support a doctrine implementation of passport. You are not paying us to do it. Nothing is stopping you from starting your own passport repo. We decided against supplying one for good reasons. You should respect that decision and don't respond in this disrespectful way anymore.

**Comment by oddz** [comment]
The only apology I would ever offer is the apology that you don't care... I find it sad... like I said nobody cares.

**Comment by patrickbrouwers** [comment]
Please stop responding, you are not helping yourself.

**Comment by oddz** [comment]
I agree with you in that regard... but you have Lavoaster whom has a pretty good solution to this problem. However, you won't accept or even look at it because it completely rewrites the module. If you actually take anytime to look at how passport is written you will see that it is TIGHTLY coupled to eloquent. So what he/she? Wrote is actually pretty good. I get that you don't want to support a completely different code base. Perhaps in the next version of Laravel we try to Negev ideas. Create a version of passport that is flexible enough to have multiple pesistence laters? There is a solution here. I'm not saying that it has to be a solution which is implanted immediately. What I want is the influence of this project to cascade up and not only improve Laravel but make it easier for projects such as Laravel doctrine to integrate with it without completely rewriting things... no one wants that.

**Comment by oddz** [comment]
My passion for this project may come off offensive and for that apologize but
 I see the js everywhere movement beginning to take over and if great ecosystems like Laravel can't implement a basic domain mapper pattern... One which is based on a tried bad true gene work I don't know what to think.

**Comment by oddz** [comment]
Patrick, your programming and/or leadership skills are much better in code than in person. Might want to work on that. Just a suggestion. I still love your shit though!

**Comment by sisve** [comment]
@oddz The way to proceed in this issue would be to change one of the large underlying issues in Laravel's passport code.

> laravel code is horribly coupled to eloquent and keeping up with the BC is not fun
Source: https://laraveldoctrine.slack.com/archives/C07HD2RS7/p1488372589003080

The decision has been made on the current state of affairs. The best way to change the decision would be to change the underlying issue, the coupling between Passport and Eloquent.

> Passport doesn't support MongoDB. It only supports Eloquent.
Source: https://github.com/laravel/passport/pull/306#issuecomment-285879831

So, boot up that propaganda- and  lobby machine, and change this underlying problem.

**Comment by oddz** [comment]
The things you did with Laravel are great I just don't agree with this decision.

**Comment by oddz** [comment]
Correct, but who wrote that? People who work on great frameworks like Laravel, ones which cater to interchangeability should not be writing the shitty, inflexible code of passport core. Sorry, but it's true. It's unacceptable to have such a tight coupling to an authentication layer that is meant to make the framework more flexible... Easier to use with other technologies.

**Comment by patrickbrouwers** [comment]
Let me start clearing up some things.

> but you have Lavoaster whom has a pretty good solution to this problem.

Never stated he didn't write a good implementation of Passport with Doctrine. 

> However, you won't accept or even look at it because it completely rewrites the module.

I have looked at it and decided against it.

> If you actually take anytime to look at how passport is written you will see that it is TIGHTLY coupled to eloquent.

Trust me, i know how tightly it's coupled to Eloquent.

> Perhaps in the next version of Laravel we try to Negev ideas. Create a version of passport that is flexible enough to have multiple pesistence laters?

In that case (case of rewrite by Laravel) we can re-evaluate this decision.

> My passion for this project may come off offensive 

Very offensive. And disrespectful against the people spending a lot of time building and maintaining this set of packages and community. 

> Patrick, your programming and/or leadership skills are much better in code than in person.

Very offensive. And very childish. So everybody who disagrees with you is per definition a bad person? 

>  It's unacceptable to have such a tight coupling to an authentication layer that is meant to make the framework more flexible... Easier to use with other technologies.

You are putting the problem in the wrong community. Laravel-Doctrine can't be helt accountable for decisions made by Laravel.

**Comment by sisve** [comment]
@oddz I've added links to the sources for those statements.

If you want to put your energy into this issue, boot up the propaganda machine and start lobbying a change in the [laravel/passport](https://github.com/laravel/passport) repository to allow persistence-ignorance so that we can easily support it without rewriting everything.

**Comment by oddz** [comment]
I mean... just write it in a way where different adaptor implentatioms are accepted. I get it that there might not have been time to do it originally. Laravel though though caters to the idea of interchangeability. Don't you go us think it is important to make this aspect interchangeable via programming to to interfaces as well. I'm just so surprised no one thought of that. It's kind of like someone said we need an oauth layer and here are some basic libraries (I love php league packages) and was just like fuck it... It works. Without considering all the things that make Laravel great. I mean if I wanted a tightly coupled framework with little to offer in terms of flexibility I would be using CodeIgnitor...

**Comment by patrickbrouwers** [comment]
This is not the location for this dicussion. It's up to Taylor to provide interchangeablity in Passport. You should open a ticket there, instead of blaming us for it.

**Comment by oddz** [comment]
We should. It's unacceptable, lax to offer such a poorly programmed solution. One which can't be changed without completely rewriting the the package. Who the fuck wrote that... It's obviously not someone who is able to anticipate the needs of framework users...

**Comment by Evertt** [comment]
@patrickbrouwers @oddz @christiandreher @Toyinster @sisve @HDsign as you can see I opened [an issue](https://github.com/laravel/passport/issues/326) on the Laravel Passport repo. Maybe you can show your support and/or add some ideas or information to the thread. :-)

**Comment by patrickbrouwers** [comment]
I have tested the integration and it's actually achievable without any customizations in Laravel Passport and Laravel Doctrine.

The only thing that doesn't work out of the box are the listing of "personal access tokens". With a small change in Laravel-Passport that would also work.

You should just embrace Eloquent for this OAuth stuff. By setting the user provider on "doctrine", the oauth token gets automatically converted to a Doctrine instance.

Currently it's necessary to have` $id` public (because Laravel-Passport uses it) and have a `getKey()` method.    

```
<?php

namespace App\Entities;

use Doctrine\ORM\Mapping AS ORM;
use Laravel\Passport\HasApiTokens;

/**
 * @ORM\Entity
 * @ORM\Table(name="users")
 */
class User
{
    use HasApiTokens;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $name;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    public function getKey()
    {
        return $this->id;
    }
}
```

config/auth.php:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => App\Entities\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

**Comment by patrickbrouwers** [comment]
Changes for Laravel Passport to make it fully compatible: https://github.com/laravel/passport/pull/327

**Comment by patrickbrouwers** [comment]
Above PR was merged. You can now use Passport together with Laravel Doctrine with the minimal change that you need to implement the `getKey()` method in your User entity.

**Comment by Evertt** [comment]
Patrick, you are amazing. :-D

**Comment by mauserrifle** [comment]
Great work!

I just tested the password grant but resulted in error:

Call to undefined method Cms3\Core\Domain\User\Entity\User::where()' in vendor/laravel/passport/src/Bridge/UserRepository.php:44

This bridge is still tight to eloquent. Or did I forget to setup something maybe?

**Comment by patrickbrouwers** [comment]
Maybe they broke it again? I thought I tested password grant too and it work last month.

**Comment by aftabnaveed** [comment]
@patrickbrouwers does the integration work? If yes is it fully stable?

**Comment by provun** [comment]
@patrickbrouwers has the code been stabilised as yet? Or should we be looking at other avenues?

**Comment by jorygeerts** [comment]
The current implementation seems broken. `Laravel\Passport\Bridge\UserRepository::getUserEntityByUserCredentials()` reads the `auth.providers.users.model` config value and assumes it is the name of a class that has a constructor without arguments and either `findForPassport` of `where` as method.

Since my entities do have constructors (with their non-nullable properties as parameters) and I do not need a `findForPassport` or `where` method in them, I created a simple class (`App\Auth\PassportDoctrineBridge`) that implements only `findForPassport` (using `App::make(UserRepository::class)` to fetch my repository) and configured that as "model". This, however, leads to an exception "No EntityManager is set-up for App\Auth\PassportDoctrineBridge".

The issue here is that Laravel Passport has one configuration option, `model`, that it uses for both the entity and the repository (which is valid for active record, because the entity and repository are the same class). In my opinion, the "proper" solution would be to get Laravel Passport changed so that it uses two different configuration options and then also support that second property in LaravelDoctrine. However, the more pragmatic approach might be to just do that second part.

I've solved this by extending `DoctrineServiceProvider`, overwriting `extendAuthManager` to change `$entity = $config['model'];` to `$entity = $config['entity'] ?? $config['model'];`. That + my `PassportDoctrineBridge` + the following configuration in `config/auth.php` works for me.
`'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => App\Auth\PassportDoctrineBridge::class,
            'entity' => App\Entities\User::class,
        ],
]`

**Comment by isaackearl** [comment]
So what is the current state of this?  Is it possible to use Laravel Doctrine with Passport?  I'm looking to start a new project and I definitely want to try using Laravel Doctrine for it.  However I'm thinking of creating an API that would highly benefit from passport.

So if I understand correctly, there was a change to the passport code base which made it possible to integrate with Laravel Doctrine... but further changes to the package once again broke it?

It also seemed like there is a workaround from reading through this thread, that I can just handle oauth with eloquent and then also map entities to the same tables etc using doctrine?  

If anybody with a bit more experience can point me in the right direction that would be great.  If it is not tenable at the moment then I'll just try and think of a new project to work on with Doctrine that doesn't need oauth.  Thanks!

**Comment by isaackearl** [comment]
So to answer my own question... I went ahead and gave the integration a try.

It ended up being fairly easy to get passport to work with doctrine.  I would go so far as to say, if you are thinking of integrating passport in your doctrine laravel app, then just go ahead and try and do it, it works well out of the box after a few fixes.  Here are the things I had to do to get things to work:

1. I had to create my own tables/migrations to create the tables needed for passport.  I created an entity mapping for each table so I could have doctrine automatically create the migration for me (that's how I did it, but you just need the tables created).  I had some issues with trying to create database columns of type "TIMESTAMP", but ended up just doing DATETIME instead and it worked just fine.  In the end that migration looked like this (I am using mysql):

```
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE oauth_access_tokens (id VARCHAR(100) NOT NULL, user_id INT DEFAULT NULL, client_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, scopes LONGTEXT DEFAULT NULL, revoked TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, expires_at DATETIME DEFAULT NULL, INDEX user_id_index (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth_auth_codes (id VARCHAR(100) NOT NULL, user_id INT NOT NULL, client_id INT NOT NULL, scopes LONGTEXT DEFAULT NULL, revoked TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth_clients (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, secret VARCHAR(100) NOT NULL, redirect LONGTEXT NOT NULL, personal_access_client TINYINT(1) NOT NULL, password_client TINYINT(1) NOT NULL, revoked TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX user_id_index (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth_personal_access_clients (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX client_id_index (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth_refresh_tokens (id VARCHAR(100) NOT NULL, access_token_id VARCHAR(100) NOT NULL, revoked TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, INDEX access_token_index (access_token_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }
```

2. I had to add one function to my User Entity.... 
```
    /**
     * @return int
     */
    public function getKey()
    {
        return $this->getId();
    }
```

That is pretty much it if I'm remembering properly.  It also failed once I tried testing my API endpoint because the default endpoint in laravel tries to return the entire user... which fails because the entities don't have a __toString() method... You can fix this and get your api endpoint working by implementing a way to serialize yoru entity or you can just change the endpoint to return something else.

```
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user()->getName();
});
```

So behind the scenes passport is still using Eloquent models to manipulate the data on the oauth tables that get created, but I don't see this as a problem at all.  The rest of your application doesn't have to worry or think about that at all and it should have no affect.  

Software used:
```
laravel-doctrine/orm                  1.3.6   A Doctrine ORM bridge for Laravel 5
laravel/framework                     v5.4.27 The Laravel Framework.
laravel/passport                      v2.0.11 Laravel Passport
```

**Comment by KPKoch** [comment]
Currently I am trying to integrate Passport with Laravel. 
Situation seems: not that easy with Passport 3.0. At least the solution suggested by isaackearl doesn't work this way for me. 

It get stucks at the "Repos" and the access via Active Record. This seem to me like some major work to integrate. The exact problem I am facing is the missing "where", like in 
"Call to undefined method App\Models\User\User::where()"
Is there some "easy" way to just overwrite it or solve this with another non-source modifying way?

Also I think passport is in modern days no optional feature, as most projects will need OAuth. Modern webapps are nowdays also an API for mobile apps - maybe for distributed services. This change is nowadays much more important then 10 years ago.
This said: Issues like this could be a real deal breaker for me to use laraveldoctrine, as the more of a time invest is a true thing with doctrine instead of eloquent. Even if I really don't want to use an active record pattern.

**Comment by isaackearl** [comment]
@KPKoch 

So I went ahead and upgraded my install to Passport 3.0 to see what the issues were, and it actually worked for me.  I think I must have done something else that I didn't document properly in my above example.

I think I'll spend some time this week setting up another project with doctrine and passport, and I'll try and do a better job of documenting it and maybe do a little write-up.  

The repo shouldn't be trying to use the "Model" for user at all.. so I'm thinking part of your configuration may be wrong.  Have you changed your user provider in auth.php ? It should look something like this:

```
    'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => App\Entities\User::class,
        ],
    ],
```

Let me know if that fixes your problem at all.

**Comment by KPKoch** [comment]
I consider that there may be some configuration error. I feel this happens sometimes while upgrading and the project is up-to-date but had a minor history (think it could have had been 5.2) and the recent change in the frontend (decision to move from a laravel web app to a API only)
At least the config is right:
    'providers' => [
        'users' => [
            'driver' => 'doctrine',
            'model' => App\Models\User\User::class,
        ],

I made this part work, by editing laravel/src/Bridge/UserRepository, getUserEntityByUserCredentials and added as quick fix a repomanager. So the question remains, why had I?

After this, there seem problems with the guard.... at least auth is empty, when asked later. 
I'll still have to check if there is something within the frontend that I have to adapt (vue with vue-passport).

Currently it breaks after the token authorization when the get to api/user is done.

**Comment by AP-Hunt** [comment]
I just want to say a massive thank you to everybody who's contributed to this issue over the last 9 months. I expect a lot of people have benefited from reading through your discussions and attempts to get Laravel-Doctrine working with Laravel Passport.

**Comment by isaackearl** [comment]
@KPKoch I went ahead and went through the process again and did a better job of documenting each thing I did.  Here is the resultant guide:

https://isaacearl.com/blog/laravel-doctrine-setup

I go through step by step.  and got a fully working passport demo at the end with doctrine etc.  I also uploaded the result to a repository here: https://github.com/isaackearl/doctrine-passport-demo

**Comment by patrickbrouwers** [comment]
@isaackearl thanks for the article! Would you mind it if I would link to it in our documentation?

**Comment by isaackearl** [comment]
@patrickbrouwers No I don't mind at all.  Sounds awesome!  I'll try and keep it up to date for those checking it out.

**Comment by patrickbrouwers** [comment]
thanks @isaackearl :)

**Comment by KPKoch** [comment]
Thx guys for the effort. Currently I still do have the problem, as I:
- cloned your example, 
+ added cors bundle (so I can test it with my current setup)
- installed packages php & js
- run passport:install
- added an user
Tried to authenticate : 
500
> Call to undefined method App\Entities\User::where()

Same place as before.  passport/src/Bridge/UserRepository.php, line 44.
If I modify this class to use the entity manager, this part works fine.

**Comment by isaackearl** [comment]
@KPKoch 

So after scratching my head for a little while I finally realized you are trying to do a Password Grant instead of an Authorization Code Grant.  

I was finally able to reproduce your issue while trying to do a password grant.  I then found a fix which I will attempt to describe to you now.  I will also update my repo and add a note to the guide I created. 

You'll see in the code for the UserRepository (where it breaks) that there is a line included to allow for a custom function to get the user.. it looks like this:

```php
if (method_exists($model, 'findForPassport')) {
    $user = (new $model)->findForPassport($username);
} else {
    $user = (new $model)->where('email', $username)->first();
}
```
So basically if you have a method "findForPassport" defined on your entity, it will do that instead of trying to use active record ->where... which is what is causing it to fail for you on line 44.  

To fix it I created the findForPassport method on my User entity... and then turned it into a trait because it looks a bit nicer.

This is what that trait looks like for me right now:

```php
trait CanUsePasswordGrant
{

    /**
     * @param string $userIdentifier
     * @return User
     */
    public function findForPassport($userIdentifier)
    {
        $userRepository = EntityManager::getRepository(get_class($this));
        return $userRepository->findOneByEmail($userIdentifier);
    }

}
```

I then just add that to my entity, and I don't have to worry about modifying any vendor files or anything like that

```php
class User implements AuthenticatableContract, CanResetPasswordContract
{

    use Authenticatable, CanResetPassword, Notifiable, HasApiTokens, Timestamps, CanUsePasswordGrant;

```

Using this approach I got the Password Grant stuff to work as well.

Let me know if you have any other questions!  

> Note: I have updated the repo, you can pull latest change and it should work. https://github.com/isaackearl/doctrine-passport-demo

**Comment by KPKoch** [comment]
I realy like your example and it helped me to find sort out a "tiny" misconfiguration from old times. My first source currently to hunt bugs. This is why it is so important to me, that examples given on the internet are just working. If they don't it adds the factor of guessing.
As said, the project is a bit older and so well the last updates with laravel were, it is always somewhat tricky to follow up all changes in the app folder - I had a depricated auth middleware.
