### ISSUE TITLE
[BUG] Rejects laravel 7 when set as a composer requirement in a repo

### ISSUE THREAD

**Issue by elb98rm** [laravel-doctrine/orm#436]
### Package version, Laravel version
orm v.1.5
Laravel 7.x

### Expected behaviour
When doctrine/orm is specified as "*" within a third party composer repo, the requirements should be met. 

### Actual behaviour
Composer error: `for laravel-doctrine/orm 1.5.5 requires illuminate/view ^6.0 `

### Steps to reproduce the behaviour
Create a laravel 7 installation (A). Then create new repo (B) with a composer dependency of `doctrine/orm: "*"`.  Attempt to include repo B as a dependency to A.

**Comment by eigan** [comment]
We currently have no version which supports L7.

**Comment by elb98rm** [comment]
> We currently have no version which supports L7.

Any plans to? ;)

**Comment by eigan** [comment]
Really busy at work with other unrelated things, so no, I have no plans as of yet. But will make sure it gets merged if someone opens a PR where tests pass :)

**Comment by barryo** [comment]
@elb98rm - I just pushed PR #438 - can you give it a try?

You'd need to update your composer with:

```
    "repositories":[
        {
            "type": "vcs",
            "url": "git@github.com:barryo/orm.git"
        }
    ],
```

and then update the package to:

```
"require": {
    "laravel-doctrine/orm": "1.6.x-dev as 1.6",
}
```

**Comment by elb98rm** [comment]
Sorry, busy week! This now works.

**Comment by eigan** [comment]
Note that we have release 1.6 with L7 support, but there is still no doctrine/migrations support available. Mainly because it looks like we will need to upgrade to doctrine/migrations 2.0 because of some dependency issues.

I noticed @patrickbrouwers released laravel-doctrine/migrations 1.4 with supposedly L7 support. But that pipeline doesnt go through, not sure if it works.

**Comment by patrickbrouwers** [comment]
` laravel-doctrine/migrations 1.4` might work. I ran into some other dependencies when trying to upgrade, so cannot confirm yet.

**Comment by josua7** [comment]
Hey mates! Something new here? You have some prevision for migrations?

Thank you in advance.

**Comment by chewbakartik** [comment]
Hey @patrickbrouwers I am having a similar issue to @eigan. I can not getting `laravel-doctrine/migrations:1.4` to work.

```
Problem 1
    - Conclusion: don't install laravel-doctrine/migrations 1.4.0
    - Conclusion: remove symfony/console v5.0.6
    - Installation request for laravel-doctrine/migrations ^1.4 -> satisfiable by laravel-doctrine/migrations[1.4.0, 1.4.x-dev].
    - Conclusion: don't install symfony/console v5.0.6
    - laravel-doctrine/migrations 1.4.x-dev requires doctrine/migrations ~1.8 -> satisfiable by doctrine/migrations[1.8.x-dev, v1.8.0, v1.8.1].
    - doctrine/migrations 1.8.x-dev requires symfony/console ~3.3|^4.0 -> satisfiable by symfony/console[3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
    - doctrine/migrations v1.8.1 requires symfony/console ~3.3|^4.0 -> satisfiable by symfony/console[3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
    - doctrine/migrations v1.8.0 requires symfony/console ^3.4||^4.0 -> satisfiable by symfony/console[3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
    - Can only install one of: symfony/console[3.3.x-dev, v5.0.6].
    - Can only install one of: symfony/console[3.4.x-dev, v5.0.6].
    - Can only install one of: symfony/console[4.0.x-dev, v5.0.6].
    - Can only install one of: symfony/console[4.1.x-dev, v5.0.6].
    - Can only install one of: symfony/console[4.2.x-dev, v5.0.6].
    - Can only install one of: symfony/console[4.3.x-dev, v5.0.6].
    - Can only install one of: symfony/console[4.4.x-dev, v5.0.6].
    - Installation request for symfony/console (locked at v5.0.6, required as ^5.0.6) -> satisfiable by symfony/console[v5.0.6].
```

**Comment by chewbakartik** [comment]
So I dug into this a little bit more, it looks like the `illuminate/console:^7.0` package of 7.0.0 has updated it's dependency to `symfony/console:^5.0`. The earliest version of `doctrine/migrations` that uses `symfony/console:5.0` is `v2.2`. I think that this issue is in the wrong repository and this information needs to get moved over to `laravel-doctrine/migrations`.

**Comment by eigan** [comment]
laravel-doctrine/migrations 2.0 is now released with support for Laravel 7, thanks to @chewbakartik! 

Note that there is some breaking changes because of the upgrade to doctrine/migrations 2.0. See the release notes here: https://github.com/laravel-doctrine/migrations/releases/tag/2.0.0

@patrickbrouwers Should we delete the 1.4 version from packagist, or what do you suggest?

**Comment by patrickbrouwers** [comment]
Yes best to delete I think. Great job on 2.0!

**Comment by eigan** [comment]
I have no access to the laravel-doctrine on packagist.org, could you do it?

**Comment by patrickbrouwers** [comment]
@eigan I've added you as maintainer to packagist and deleted the 1.4 release

**Comment by eigan** [comment]
@josua7 and @elb98rm: using laravel-doctrine with Laravel 7 should now work. See https://github.com/laravel-doctrine/migrations/issues/93#issuecomment-609462080 if you use laravel-doctrine/migrations.
