### ISSUE TITLE
[QUESTION] Support API Resources?

### ISSUE THREAD

**Issue by MP-okui** [laravel-doctrine/orm#450]
[Laravel 7.x Eloquent: API Resources
](https://readouble.com/laravel/7.x/en/eloquent-resources.html)

### Package version, Laravel version

- laravel-doctrine/orm 1.6.0
- laravel/framework 7.17.2

### Expected behaviour

return JSON

### Actual behaviour

Call to undefined method Doctrine\ORM\PersistentCollection::mapInto()

### Steps to reproduce the behaviour

```php
use App\Doctrine\Entities\Book;
use App\Http\Resources\Book as BookResource;
use LaravelDoctrine\ORM\Facades\EntityManager;

Route::get('/books', function () {
    return BookResource::collection(
        EntityManager::getRepository(Book::class)->findAll()
    );
});
```

**Comment by dpslwk** [comment]
API Resources are expecting the underlying resource to be  either `Arrayable` or `JsonSerializable`
Both of which Eloquent models get for free since they extend `Model`
As Entities are just Plain Objects this is down to the user to implement.

Three methods I have used/know

1) **Do it in the API Resource**

A freshly made API resource has the following 
```
    public function toArray($request)
    {
        return parent::toArray($request);
    }
```

flesh that out with exactly what you want returned
any method on the Entity can be called (not sure if properties can be directly access)
```
    public function toArray($request)
    {
        return [
            'id' => $this->getId(),
            'name' => $this->getFirstname(),
            'lastname' => $this->getLastname(),
            'username' => $this->getUsername(),
            'email' => $this->getEmail(),
            'profile' => new ProfileResource($this->getProfile()),
        ];
    }
```


2) **Do it in the Entity with out the box traits**

There is already a basic `Arrayable` serialiser include, but YMMV when it hits a date/datetime if you use `Carbon`
`LaravelDoctrine\ORM\Serializers\Arrayable`

just throw this on the entity you are trying to Resource 

```
use LaravelDoctrine\ORM\Serializers\Arrayable;
use Illuminate\Contracts\Support\Arrayable as ArrayableContract;

class Building implements ArrayableContract
{
    use Arrayable;

```



3) **Do it on the Entity by hand**

add a `toArray()` and if you like an `toJoson()` method on your Entity
and implement `Arrayable `/ `JsonSerializable`

Here is an cutdown example from my project
```
use JsonSerializable;
use Illuminate\Contracts\Support\Arrayable as ArrayableContract;

class BookableArea implements ArrayableContract, JsonSerializable
{

    ....

    /**
     * @return array
     */
    public function toArray()
    {
        return [
            'id' => $this->getId(),
            'name' => $this->getName(),
            'description' => $this->getDescription(),
            'maxOccupancy' => $this->getMaxOccupancy(),
            'additionalGuestOccupancy' => $this->getAdditionalGuestOccupancy(),
            'bookingColor' => $this->getBookingColor(),
            'bookingColorString'  => $this->getBookingColorString(),
            'selfBookable' => $this->isSelfBookable(),
            'building' => $this->getBuilding(),
        ];
    }

    public function jsonSerialize()
    {
        return $this->toArray();
    }
}
```

**Comment by dpslwk** [comment]
hmm just looked at your error again
you may not have even hit the need for the stuff I mentioned above but I suspect you will

I never had the error with `Doctrine\ORM\PersistentCollection::mapInto()` since I use the repository pattern and am always passing a plain array to `::collection(` not a `PersistentCollection`, stick a `toArray()` after the `findAll()`
see what happens

**Comment by MP-okui** [comment]
@dpslwk 
Thank you.
```toArray()``` solved the problem.

```php
Route::get('/books', function () {
    return BookResource::collection(
        EntityManager::getRepository(Book::class)->findAll()->toArray()
    );
});
```
