### ISSUE TITLE
[BUG] Error Class "Doctrine\Common\Cache\ArrayCache" not found

### ISSUE THREAD

**Issue by aftabnaveed** [laravel-doctrine/orm#493]
### 1.7, 8.45

I configured a brand new Laravel application and installed the latest version of `Laravel Doctrine`  when trying to navigate to a page or execute an `artisan` command I get that error. Do you know why would this be happening?

**Comment by aftabnaveed** [comment]
Looks like `ArrayCache` is deprecated in `doctrine/cache:2.0`   
https://github.com/doctrine/cache/pull/355

Would it be safe to remove it from `Laravel Doctrine` ?

**Comment by eigan** [comment]
We should probably lock to doctrine/cache 1.* for know.

**Comment by eigan** [comment]
Released a version which locks to ^1 now. 

Should look into finding replacements. Maybe symfony/cache.

**Comment by aftabnaveed** [comment]
Yes, symfone/cache sounds better.

**Comment by vvval** [comment]
if php ^8.0` needed, doctrine/common will be locked to a version without cache. 
`php artisan package:discover` causes error even if `symfony/cache` is required

**Comment by rakshitbharat** [comment]
Having same error
Guys please do something, My almost 2 projects failed in staging server

**Comment by eigan** [comment]
@rakshitbharat we did. See the comments. What versions are you using? Both from laravel-doctrine and doctrine.

**Comment by cesaric** [comment]
@dpslwk  closed it because the fix didn't seem to work out.

I'm on versions (php 8.1) :
laravel-doctrine: 1.7.7
doctrine/orm: 2.11.2
doctrine/cache:  2.1.1

It doesn't appear that we have the Doctrine\Common\Cache\{ArrayCache, FileSystemCache, etc..} in doctrine/cache 2.x but it's being referenced in places like laravel-doctrine/orm/src/Configuration/Cache/FileCacheProvider.php.

Adding/locking  "doctrine/cache": "^1.12.1" to composer.json does fix it since doc/orm works with either.
