### ISSUE TITLE
[BUG] The `Auth\Passwords\DoctrineTokenRepository` creates tokens without hashing

### ISSUE THREAD

**Issue by rosamarsky** [laravel-doctrine/orm#506]
I used the default Illuminate Password Broker before I found in your documentation [This page](http://laraveldoctrine.org/docs/1.4/orm/passwords)
After changing `PasswordResetServiceProvider` in config/app.php I checked the table `password_resets` and saw not hashed tokens. It looks really unsafe. 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/15215861/145599255-320c7cab-22b0-4ef5-9d55-24bf2911e01c.png">

_Package version 1.4, Laravel version 8.0_

**Comment by dpslwk** [comment]
I believe that that token is generated here 
https://github.com/laravel-doctrine/orm/blob/2824a8516ac8b5b812d7195f01c7c64470abc179/src/Auth/Passwords/DoctrineTokenRepository.php#L213-L221

which just results on a different Hash/Token that laravel which is likely using there built in Hash Facade

**Comment by dpslwk** [comment]
ah laravel are building it the same but are pushing the token through the hasher before it goes into the database

https://github.com/laravel/framework/blob/cf00a5621f2eacdb978d3176e6d601193d9dc57d/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php#L207-L215

https://github.com/laravel/framework/blob/cf00a5621f2eacdb978d3176e6d601193d9dc57d/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php#L111-L121


Happy to take  PR to fix this, but it might be considered a BC, since it would invalidate all existing tokens
