### ISSUE TITLE
[PROPOSAL] Maintenance of this package and the community around it

### ISSUE THREAD

**Issue by superbiche** [laravel-doctrine/orm#512]
Hi,

I usually don't like this kind of issues but regarding the current state of this package and unresponsiveness of most of its maintainers (@eigan thanks for the latest release), I'm offering - on behalf of my company but without any marketing or promotional hidden objective - to take over maintenance of this package and the community tools around it (Slack, Docs...).

#489 was opened 6 months ago. Some people like https://github.com/aftabnaveed are using it in critical applications - just like we do - and offered to contribute.
#479 was opened for even longer. Still nothing.

11 months later the community Slack is still down - @josenicomaia told on #489 it would be fixed the day after, we're 6 months later.
I totally understand that people change careers, paths, objectives and main focuses. 2020 and 2021 dramatically changed everyone's life, so I'm not judging anyone.

But, if maintainers are not available, have different focuses, or had some bad surprises in their lives, while it is totally understandable - this is OSS so nobody should expect them to dedicate their time to any free project - at least they should make it easy for motivated people willing to contribute _efficiently_ (meaning, not waiting for weeks or months for issues to be answered or PRs to be reviewed) to actually do it.

We're also using Laravel Doctrine for a critical website and would be more than happy to be involved - or take over - maintainance of this package with anyone interested and ready to give some time in reviewing, documenting, or writing code, like many already offered. 

@eigan did a release pretty recently but apparently doesn't use this package anymore. It doesn't make sense to leave them the responsibility of moving this package forward while not having any interest in doing it.
Many people are still using it daily in critical applications and I'm pretty sure we could build a new, more flexible team together to start again.

I don't want to force anyone's hand but maybe it's time to move forward and give the responsibility to people who can actually dedicate time to maintain it. 
Otherwise why not let it die, fork it, create a new community with a suffixed name... This would be an avoidable effort, but I'd rather do that than rewrite our apps. 

Again, sorry if this seems like an aggressive approach. I'm just trying to make this project move forward as we really depend on it, just like many people here. 

I hope I wasn't disrespectful and apologize in advance if anyone was hurt by these words.

Wish you all the best for this new year, take care of yourselves and your loved ones.

**Comment by FoxxMD** [comment]
I can't speak for eigan as we haven't communicated in a long time but as a former maintainer (and one of the people who brought them on initially) I think I can say with confidence that any lack of development or communication with regards to maintaining this library is definitely related to circumstance and not a personal flaw :)

This library should absolutely be maintained and any amount of effort from you or the community is greatly appreciated. I'd like to give @eigan an opportunity to chime in but I'm happy to give you maintainer access.

Regarding your other points...

### Website 

It's running on laravel which means it needs an actual server somewhere. This is probably the biggest change but it greatly benefit the community if the docs were a static website hosted on `gh-pages` and the domain just CNAME'd to that instead. Would make updating docs much easier since they could even be done with github actions (to re-generate the static site).

### Support Channel (Slack)

Slack is...not the greatest anymore. It's too centralized. It would probably be better to switch to Discord or better yet Gitter so support isn't so dependent on one administrator.

EDIT: Created some gitter rooms for the community:

* [general](https://gitter.im/laravel-doctrine/community)
* [orm](https://gitter.im/laravel-doctrine/orm)

**Comment by eigan** [comment]
Hi @superbiche :)

My somewhat related comment regarding this: https://github.com/laravel-doctrine/migrations/issues/113#issuecomment-908629100 
Just to clarify, we actually do use laravel-doctrine/orm and laravel-doctrine/migrations, but it's one (huge) application and we mostly spend time in domain-logic. We do not use any other Laravel packages like Octane. Which is why you will not see me adding any value to laravel-doctrine, simply because it doesn't give our customer any value (and I don't work much off-hours). 

I was added as a maintainer to help review, merge and release contributions from the community at a time when PRs was piling up. Yes, there is still PR's and issues open and I am sorry for that. Some PR's introduce code and fixes to part of Laravel that we (our company) don't even use, so it's difficult for me to have any opinion about whether we (laravel-doctrine) want to solve it like the contributor have solved it, or if another approach is favorable.  It makes me sad that I am not able to see the best way forward for laravel-doctrine and at the same time is the only person actually deciding what's get into it. 

That said, I am very glad for every contributors and PRs provided by the community. They have been very good and helped the project stay stable (for us at least) for a long time, and even support for latest three Laravel versions, PHP 8, and several doctrine versions, which is great. 

If someone wants to take over, and with the support of a company, great! I will not be in the way.

**Comment by superbiche** [comment]
Hi @FoxxMD and @eigan and thanks so much for spending some time on such constructive answers. I misunderstood the fact that @eigan had to ask other maintainers about the Slack status, and thought pretty much no one was able to maintain this package properly. 
But if you want to keep maintaining it we'd be - me and one or two teammates - happy to give support, participate in maintaining it and maybe move the community channels over to Discord and built a static website.  

I'll join over the Gitter channels - thanks for creating these btw - and maybe we can discuss there how best we can all help move this project forward. 

Again thanks for your replies and for not taking my initiative as anything hostile or disrespectful, much appreciated. 

Have a nice weekend and stay safe
