### ISSUE TITLE
[BUG] Laravel 11 "validation.presence" not overriden

### ISSUE THREAD

**Issue by xaben** [laravel-doctrine/orm#576]
Laravel 11 upgrade not possible due to all the validations failing as service is not being overridden.

### Package version, Laravel version
laravel-doctrine/orm 2.1.0
laravel/framework v11.10.0

### Expected behaviour

LaravelDoctrine\ORM\Validation\DoctrinePresenceVerifier is returned when trying to fetch "validation.presence" service

### Actual behaviour

Illuminate\Validation\DatabasePresenceVerifier is returned instead

### Steps to reproduce the behaviour

Add an Exists validation as described in https://laraveldoctrine.org/docs/1.8/orm/validation

**Comment by dretsa** [comment]
I manager to solve this by adding the following to my AppServiceProvider:
```php
$this->app->singleton(DoctrinePresenceVerifier::class);
$this->app->extend('validation.presence', fn () => app()->get(DoctrinePresenceVerifier::class));
```

A bit hacky but a step in the right direction. I can look into submitting a PR this weekend.

**Comment by cheack** [comment]
Another workaround is to downgrade to Laravel v11.8.0 - the bug is reproducible since v11.9.0.

**Comment by TomHAnderson** [comment]
@dretsa  If you get around to a PR (if, in fact, this repo is the problem and not Laravel), I will look forward to it.

**Comment by dpslwk** [comment]
its still all broken, even testing on the fresh L12 and latest orm
`unique` and `exists` validation rules are not over ridden

this is since Laravel 11.9.0 where https://github.com/laravel/framework/pull/51343 made some changes to Application::getProvider() 
and its broken the loading some how of inheritance in service providers
https://github.com/laravel/framework/issues/51739


found at the solution 
`config/app.php`

```
'providers' => Illuminate\Support\ServiceProvider::defaultProviders()
        ->except([
            Illuminate\Validation\ValidationServiceProvider::class,
        ])
        ->toArray(),
```
