### ISSUE TITLE
[1.1] Easier Timestampable and Softdeletable

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel-doctrine/orm#89]
- Provide an own implementation of Timestampable and Softdeletable
- Should support all mapping drivers (Fluent as well)
- No Gedmo extensions needed
- Support both Carbon and DateTime, right date strategy should be choosen

**Comment by Zn4rK** [comment]
It would be cool if this implementation could work with fetch="EXTRA_LAZY", on the relation, which by the looks of it, doesn't work with Gedmo's SoftDeleteable.

**Comment by patrickbrouwers** [comment]
Not sure if we have that in our hands or that's an issue in Doctrine's filter system.

**Comment by Zn4rK** [comment]
It looks like it's a limitation (or a feature) in [PersistentCollection::removeElement()](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/PersistentCollection.php#L373). So it might be a bit hard. Forcing the collection to be fetched before removing an element solves this case, but does not feel like a good solution.

**Comment by dave-redfern** [comment]
I know this issue is a little old, but if it helps at all I implemented a few of these behaviours: https://github.com/dave-redfern/laravel-doctrine-behaviours It's done via interfaces and listeners, so the only thing needed in mappings are the fields. If there is anything useful, feel free to help yourselves.

**Comment by patrickbrouwers** [comment]
@dave-redfern  we are considering adding "community packages" to the website. Will add your link :)
